version: "3.7"
services:
  database_treinamento:
    image: mysql
    container_name: database_treinamento
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: code
      MYSQL_USER: admin
      MYSQL_PASSWORD: docker
      TZ: "America/Sao_Paulo"
    volumes:
      - mysql:/var/lib/mysql
    network_mode: host
  app:
    build: .
    container_name: b2s
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host
volumes:
  mysql:
    driver: local
